# -*- coding: utf-8 -*-
"""cobaseaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mxc9yb9w5NB-T3HwbniNY0zfEjpPWnaN
"""

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/My Drive/Kaggle"
# /content/gdrive/My Drive/Kaggle is the path where kaggle.json is present in the Google Drive

# Commented out IPython magic to ensure Python compatibility.
#changing the working directory
# %cd /content/gdrive/My Drive/Kaggle
#Check the present working directory using pwd command

!kaggle datasets download -d jilkothari/finance-accounting-courses-udemy-13k-course

!ls

#unzipping the zip files and deleting the zip files
!unzip \*.zip  && rm *.zip

# Importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
sns.set()

df = pd.read_csv(r'udemy_output_All_Finance__Accounting_p1_p626.csv')

df.head()

# Displaying last 5 rows
df.tail()

print(df.columns.values)

df.info()

# Checking if all the ID column values are unique
df['id'].unique().size

# Descriptive statistics
df.describe(include='all')

# Displaying all column names again
print(df.columns.values)

# Renaming 'price_detail__amount' to 'price'
df = df.rename(columns={'price_detail__amount': 'price'})

# Distribution of course prices
sns.displot(df['price'], kde=True)
plt.show()

# Checking for outliers in price column
sns.boxplot(x=df['price'])
plt.show()

# Distribution of number of subscribers
sns.displot(df['num_subscribers'], kde=True)
plt.show()

# Distribution of average ratings
sns.displot(df['avg_rating'], kde=True)
plt.show()

# Distribution of Recent Average Ratings
sns.displot(df['avg_rating_recent'], kde=True)
plt.show()